### ISSUE TITLE
我来了！初步测试结果

### ISSUE THREAD

**Issue by jiangshanghan** [wxwmoe/wxwClub#1]
@ 数目＞1时，ovost没有自动转帖。（进入share box？）
自动转帖有一定延时，目前可能是10分钟内。（这倒不是一个很严重的问题）
未明确：新建ost如何使display name呈现汉字。（后期应该会再更新）
既然整了新项目，是不是投一下#guppe 写个双语广而告之一波

**Comment by fghrsh** [comment]
(> ʌ <) 目前项目还在开发阶段，不稳定的地方比较多，不适合投到 #guppe ...

**Comment by jiangshanghan** [comment]
> 
> 
> (> ʌ <) 目前项目还在开发阶段，不稳定的地方比较多，不适合投到 #guppe ...

其实……
如果投tag
然后可以召集网友一起参与修改升级啊
我看另一个人就是之前在tag放置了征集
像这 [帖文链接](https://social.coop/@datatitian/107066314691139967)

**Comment by jiangshanghan** [comment]
# update

新建ovo.st及在帖文中@该帐户，

删除并修改，

未能成立
