### ISSUE TITLE
关于Tombstone

### ISSUE THREAD

**Issue by Rei-Ruimin** [wxwmoe/wxwClub#2]
你好！请问可以讲解一下什么样的消息会被归类为旧消息并撤销转发吗？我的理解是同一个账户在同一天删除已被同一个群组发出的嘟文之后，如果ta想再次再次从此群组发出嘟文就会被认定为tombstone，然后需要等到第二天才可以发送成功，这样对吗？
php小白有点不理解在controller.php中这一段的含义 > <
![image](https://user-images.githubusercontent.com/60533945/166410608-1f5985a3-b70c-4d32-b2b4-d5c99c48f752.png)

**Comment by fghrsh** [comment]
这个 Tombstone 是旧消息的删除通知，由用户所在服务器专门发来通知的（用户 @ 了群组所以有通知）
会触发这个消息，说明用户手动删除了那条；因为原文删除了，所以这边也通知下其他服务器，撤销转发

**Comment by Rei-Ruimin** [comment]
好的！多谢解答😊
